version: '2.1'

networks:
  coffee_net:
  validator_net:

services:
  # ============================================================================
  # CONSORTIUM NETWORK SERVICES
  # ============================================================================
  
  # Orderer Organization
  orderer.coffee-consortium.com:
    container_name: orderer.coffee-consortium.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./network/organizations/ordererOrganizations/coffee-consortium.com/orderers/orderer.coffee-consortium.com/msp:/var/hyperledger/orderer/msp
      - ./network/organizations/ordererOrganizations/coffee-consortium.com/orderers/orderer.coffee-consortium.com/tls:/var/hyperledger/orderer/tls:ro
      - ./network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    ports:
      - 7050:7050
    networks:
      - coffee_net

  # CouchDB for National Bank
  couchdb.nationalbank.com:
    container_name: couchdb.nationalbank.com
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 15984:5984
    networks:
      - coffee_net

  # National Bank Organization
  peer0.nationalbank.com:
    container_name: peer0.nationalbank.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_ID=peer0.nationalbank.com
      - CORE_PEER_ADDRESS=peer0.nationalbank.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nationalbank.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nationalbank.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nationalbank.com:7051
      - CORE_PEER_LOCALMSPID=NationalBankMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/nationalbank.com/peers/peer0.nationalbank.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/nationalbank.com/peers/peer0.nationalbank.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/nationalbank.com/peers/peer0.nationalbank.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/organizations/peerOrganizations/nationalbank.com/users/Admin@nationalbank.com/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./network/organizations:/etc/hyperledger/fabric/organizations
      - ./network/channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - peer0.nationalbank.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7052:7052
      - 9443:9443
    networks:
      - coffee_net

  # CouchDB for Exporter Bank
  couchdb.exporterbank.com:
    container_name: couchdb.exporterbank.com
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 15985:5984
    networks:
      - coffee_net

  # Exporter Bank Organization
  peer0.exporterbank.com:
    container_name: peer0.exporterbank.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_ID=peer0.exporterbank.com
      - CORE_PEER_ADDRESS=peer0.exporterbank.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.exporterbank.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.exporterbank.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.exporterbank.com:8051
      - CORE_PEER_LOCALMSPID=ExporterBankMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/exporterbank.com/peers/peer0.exporterbank.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/exporterbank.com/peers/peer0.exporterbank.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/exporterbank.com/peers/peer0.exporterbank.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/organizations/peerOrganizations/exporterbank.com/users/Admin@exporterbank.com/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.exporterbank.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP=20
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./network/organizations:/etc/hyperledger/fabric/organizations
      - ./network/channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - peer0.exporterbank.com:/var/hyperledger/production
    ports:
      - 8051:8051
      - 8052:8052
      - 9444:9444
    networks:
      - coffee_net

  # CouchDB for Coffee Authority
  couchdb.coffeeauthority.com:
    container_name: couchdb.coffeeauthority.com
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 15986:5984
    networks:
      - coffee_net

  # Coffee Authority Organization
  peer0.coffeeauthority.com:
    container_name: peer0.coffeeauthority.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_ID=peer0.coffeeauthority.com
      - CORE_PEER_ADDRESS=peer0.coffeeauthority.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.coffeeauthority.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.coffeeauthority.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.coffeeauthority.com:9051
      - CORE_PEER_LOCALMSPID=CoffeeAuthorityMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/coffeeauthority.com/peers/peer0.coffeeauthority.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/coffeeauthority.com/peers/peer0.coffeeauthority.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/coffeeauthority.com/peers/peer0.coffeeauthority.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/organizations/peerOrganizations/coffeeauthority.com/users/Admin@coffeeauthority.com/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9445
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.coffeeauthority.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP=20
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./network/organizations:/etc/hyperledger/fabric/organizations
      - ./network/channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - peer0.coffeeauthority.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9052:9052
      - 9445:9445
    networks:
      - coffee_net

  # CouchDB for Customs
  couchdb.customs.com:
    container_name: couchdb.customs.com
    image: couchdb:3.3
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - 15987:5984
    networks:
      - coffee_net

  # Customs Organization
  peer0.customs.com:
    container_name: peer0.customs.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_ID=peer0.customs.com
      - CORE_PEER_ADDRESS=peer0.customs.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.customs.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.customs.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.customs.com:10051
      - CORE_PEER_LOCALMSPID=CustomsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/customs.com/peers/peer0.customs.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/customs.com/peers/peer0.customs.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/customs.com/peers/peer0.customs.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/organizations/peerOrganizations/customs.com/users/Admin@customs.com/msp
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9446
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.customs.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_LEDGER_STATE_COUCHDBCONFIG_MAXRETRIESONSTARTUP=20
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./network/organizations:/etc/hyperledger/fabric/organizations
      - ./network/channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
      - peer0.customs.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10052:10052
      - 9446:9446
    networks:
      - coffee_net

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ADDRESS=peer0.nationalbank.com:7051
      - CORE_PEER_LOCALMSPID=NationalBankMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nationalbank.com/peers/peer0.nationalbank.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nationalbank.com/users/Admin@nationalbank.com/msp
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/coffee-consortium.com/orderers/orderer.coffee-consortium.com/msp/tlscacerts/tlsca.coffee-consortium.com-cert.pem
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 9999999'
    volumes:
      - /var/run/:/host/var/run/
      - ./network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./network/configtx.yaml:/etc/hyperledger/fabric/configtx.yaml
      - ./chaincode:/opt/gopath/src/github.com/chaincode
    networks:
      - coffee_net
    depends_on:
      - orderer.coffee-consortium.com
      - peer0.nationalbank.com
      - peer0.exporterbank.com
      - peer0.coffeeauthority.com
      - peer0.customs.com

  # CouchDB instances for each organization
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    networks:
      - coffee_net

  couchdb1:
    container_name: couchdb1
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "6984:5984"
    networks:
      - coffee_net

  couchdb2:
    container_name: couchdb2
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "7984:5984"
    networks:
      - coffee_net

  couchdb3:
    container_name: couchdb3
    image: couchdb:3.3.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "8984:5984"
    networks:
      - coffee_net

  # ============================================================================
  # VALIDATOR SERVICES
  # ============================================================================
  
  # Build base validator image
  validator-base:
    build:
      context: .
      dockerfile: validators/Dockerfile.base
    image: validator-base:latest
    networks:
      - validator_net

  # National Bank License Validator
  nb-api:
    build:
      context: .
      dockerfile: validators/national-bank/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VALIDATOR_TYPE=LICENSE
      - VALID_LICENSES=${TEST_LICENSE_HASH}
    depends_on:
      - validator-base
    networks:
      - validator_net
      - coffee_net

  # Bank Invoice Validator
  bank-api:
    build:
      context: .
      dockerfile: chaincode/bank-api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VALIDATOR_TYPE=INVOICE
      - VALID_INVOICES=${TEST_INVOICE_HASH}
    depends_on:
      - validator-base
    networks:
      - validator_net
      - coffee_net

  # Quality Authority Validator
  quality-api:
    build:
      context: .
      dockerfile: validators/quality-authority/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - VALIDATOR_TYPE=QUALITY
      - VALID_QUALITY_CERTS=${TEST_QUALITY_HASH}
    depends_on:
      - validator-base
    networks:
      - validator_net
      - coffee_net

  # Customs Shipping Validator
  customs-api:
    build:
      context: .
      dockerfile: validators/customs/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - VALIDATOR_TYPE=SHIPPING
      - VALID_SHIPPING_DOCS=${TEST_SHIPPING_HASH}
    depends_on:
      - validator-base
    networks:
      - validator_net
      - coffee_net

  api-gateway:
    build:
      context: ./api-gateway
      args:
        - GO_MOD=-mod=vendor
    ports:
      - "8000:8000"
    volumes:
      - ./network/organizations:/etc/hyperledger/fabric/organizations
    networks:
      - coffee_net
      - validator_net
    environment:
      - LICENSE_VALIDATOR_ENDPOINT=https://nb-api:8080/validate
      - INVOICE_VALIDATOR_ENDPOINT=https://bank-api:5000/validate
      - QUALITY_VALIDATOR_ENDPOINT=https://quality-api:8081/validate
      - SHIPPING_VALIDATOR_ENDPOINT=https://customs-api:8082/validate
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/organizations/peerOrganizations/exporterbank.com/peers/peer0.exporterbank.com/tls/ca.crt
      - CORE_PEER_TLS_ENABLED=true

volumes:
  peer0.nationalbank.com:
  peer0.exporterbank.com:
  peer0.coffeeauthority.com:
  peer0.customs.com: