# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # National Bank
  # ---------------------------------------------------------------------------
  - Name: NationalBank
    Domain: nationalbank.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 2

  # ---------------------------------------------------------------------------
  # Exporter Bank
  # ---------------------------------------------------------------------------
  - Name: ExporterBank
    Domain: exporterbank.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 2

  # ---------------------------------------------------------------------------
  # Coffee Authority
  # ---------------------------------------------------------------------------
  - Name: CoffeeAuthority
    Domain: coffeeauthority.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 2

  # ---------------------------------------------------------------------------
  # Customs
  # ---------------------------------------------------------------------------
  - Name: Customs
    Domain: customs.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 2