# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdererOrg
    Domain: coffee-consortium.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete specification
    # ---------------------------------------------------------------------------
    # Count: 1
    #   CommonName: foo@wonderful.com
    #   SANS:
    #     - "bar.wonderful.com"
    #     - "alt.wonderful.com"
    #   Hostname: bar # (Optional) The name to use for the node
    #   CommonName: bar # (Optional) The username used for the node
    #   SANS: # (Optional) Additional hostnames to add to the node
    #     - "alt.wonderful.com"
    #     - "another.wonderful.com"
    # ---------------------------------------------------------------------------
    # "Users" - See PeerOrgs for user-specification format
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
