OrdererOrgs:
  - Name: Orderer
    Domain: coffee-consortium.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
          - 127.0.0.1
          - orderer.coffee-consortium.com
